#!/usr/bin/env bash
# Build script for boilerplate-cli-ui-deno
#
# Generates src/ui_gen.ts from the web UI, then compiles the CLI entry point to
# a single binary. The UI is a real module import rather than a textual
# placeholder substitution, so `deno compile` follows one import graph.
set -euo pipefail
cd "$(dirname "$0")"

DENO="${DENO:-deno}"
command -v "$DENO" >/dev/null 2>&1 || { echo "error: '$DENO' not found (set DENO=/path/to/deno)" >&2; exit 1; }

APP_NAME="boilerplate-cli-ui-deno"
WEBUI_DIR="interfaces/webui/public"

echo "Embedding the UI..."
"$DENO" run --allow-read --allow-write - <<'TS'
const dir = "interfaces/webui/public";
const files: Record<string, string> = {
  "/index.html": await Deno.readTextFile(`${dir}/index.html`),
  "/styles.css": await Deno.readTextFile(`${dir}/styles.css`),
  "/app.js": await Deno.readTextFile(`${dir}/app.js`),
};
await Deno.writeTextFile(
  "src/ui_gen.ts",
  "// Generated by build.sh — do not edit. Edit interfaces/webui/public instead.\n" +
    "export const STATIC_FILES: Record<string, string> = " +
    JSON.stringify(files, null, 2) + ";\n",
);
TS

echo "Building ${APP_NAME}..."
"$DENO" compile --allow-net --allow-read --allow-write --allow-env --allow-run \
  -o "${APP_NAME}" src/cli.ts

echo "Built: ./${APP_NAME}"
ls -lh "${APP_NAME}"
