// ─── Embedded Static Files ──────────────────────────────────────
// Generated by build.sh into src/ui_gen.ts and compiled into the binary.
import { STATIC_FILES } from "./ui_gen.ts";
import { guideJSON, llmsTxt, TOOL, VERSION } from "./guide.ts";

// ─── MIME Types ─────────────────────────────────────────────────
const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".json": "application/json",
};

// ─── Config Management ──────────────────────────────────────────
interface Config {
  setting: string;
  speedPreset: string;
}

const CONFIG_FILE = ".cliui-config.json";

async function loadConfig(): Promise<Config> {
  try {
    const data = await Deno.readTextFile(CONFIG_FILE);
    return JSON.parse(data);
  } catch {
    return { setting: "", speedPreset: "normal" };
  }
}

async function saveConfig(config: Config): Promise<void> {
  await Deno.writeTextFile(CONFIG_FILE, JSON.stringify(config, null, 2));
}

// ─── Server ─────────────────────────────────────────────────────

/// The host/port the server actually bound. /_shutdown is token-gated whenever
/// the host is not loopback (cli-daemon-spec §3).
let boundHost = "127.0.0.1";
let boundPort = 8080;

function isLoopback(host: string): boolean {
  return host === "127.0.0.1" || host === "localhost" || host === "::1";
}

function shutdownAuthorized(req: Request): boolean {
  if (isLoopback(boundHost)) return true;
  const token = Deno.env.get("SHUTDOWN_TOKEN") ?? "";
  return token !== "" && req.headers.get("X-Shutdown-Token") === token;
}

async function handler(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const path = url.pathname;

  // CORS headers
  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };

  // Handle preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers });
  }

  // ─── Daemon lifecycle (cli-daemon-spec §2, §3) ────────────────
  if (path === "/_health") {
    // Open and cheap: liveness only, no dependency checks.
    return Response.json(
      { ok: true, service: TOOL, pid: Deno.pid, port: boundPort },
      { headers },
    );
  }

  if (path === "/_shutdown") {
    if (req.method !== "POST") {
      return Response.json(
        { ok: false, error: { code: 85, type: "method_not_allowed", message: "POST /_shutdown", recoverable: false } },
        { status: 405, headers },
      );
    }
    if (!shutdownAuthorized(req)) {
      // 403, and the process MUST NOT stop.
      return Response.json(
        {
          ok: false,
          error: {
            code: 90,
            type: "forbidden",
            message: "X-Shutdown-Token required when bound off-loopback",
            recoverable: false,
          },
        },
        { status: 403, headers },
      );
    }
    // Answer before exiting, so the caller learns the request was accepted.
    setTimeout(() => Deno.exit(0), 50);
    return Response.json({ ok: true, stopping: true }, { headers });
  }

  // ─── The guide over HTTP (cli-guide-spec §3) ──────────────────
  if (path === "/guide") {
    return new Response(guideJSON(), {
      headers: { ...headers, "Content-Type": "application/json" },
    });
  }
  if (path === "/llms.txt") {
    return new Response(llmsTxt(), {
      headers: { ...headers, "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  // API Routes
  if (path === "/api/status") {
    const config = await loadConfig();
    return Response.json(
      {
        status: "running",
        port: boundPort,
        version: VERSION,
        setting: config.setting || "Not configured",
        speedPreset: config.speedPreset || "normal",
      },
      { headers },
    );
  }

  if (path === "/api/health") {
    return Response.json(
      { status: "ok", timestamp: new Date().toISOString() },
      { headers }
    );
  }

  if (path === "/api/config" && req.method === "GET") {
    const config = await loadConfig();
    return Response.json(config, { headers });
  }

  if (path === "/api/config" && req.method === "POST") {
    const config = await req.json();
    await saveConfig(config);
    return Response.json({ success: true, config }, { headers });
  }

  if (path === "/api/stats") {
    const config = await loadConfig();
    return Response.json(
      {
        setting: config.setting || "Not configured",
        speedPreset: config.speedPreset || "normal",
        runtime: "deno",
        version: "1.0.0",
        timestamp: new Date().toISOString(),
      },
      { headers }
    );
  }

  if (path === "/api/process" && req.method === "POST") {
    const { setting, speed } = await req.json();
    if (!setting) {
      return Response.json(
        { error: "Setting is required" },
        { status: 400, headers }
      );
    }

    const speedSettings: Record<string, { sleepBetweenOps: number; batchSize: number }> = {
      turbo: { sleepBetweenOps: 0, batchSize: 500 },
      fast: { sleepBetweenOps: 10, batchSize: 200 },
      normal: { sleepBetweenOps: 50, batchSize: 100 },
      gentle: { sleepBetweenOps: 100, batchSize: 50 },
    };
    const settings = speedSettings[speed] || speedSettings.normal;

    // Streaming response
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      start(controller) {
        const totalSteps = 100;
        let current = 0;

        const processChunk = () => {
          if (current > totalSteps) {
            controller.enqueue(
              encoder.encode(
                JSON.stringify({
                  type: "complete",
                  result: { setting, totalSteps, duration: "2.50", speedSettings: speed, success: true },
                }) + "\n"
              )
            );
            controller.close();
            return;
          }

          controller.enqueue(
            encoder.encode(
              JSON.stringify({
                type: "progress",
                percentage: Math.min(Math.round((current / totalSteps) * 100), 100),
                message: `🔄 Processing: ${current}/${totalSteps}`,
              }) + "\n"
            )
          );

          current += settings.batchSize;
          setTimeout(processChunk, settings.sleepBetweenOps);
        };

        processChunk();
      },
    });

    return new Response(stream, {
      headers: {
        ...headers,
        "Content-Type": "application/json",
        "Transfer-Encoding": "chunked",
      },
    });
  }

  // Static files
  if (STATIC_FILES[path]) {
    const ext = path.split(".").pop() || "";
    return new Response(STATIC_FILES[path], {
      headers: {
        ...headers,
        "Content-Type": MIME_TYPES[`.${ext}`] || "text/plain",
      },
    });
  }

  // Default to index.html
  return new Response(STATIC_FILES["/index.html"], {
    headers: {
      ...headers,
      "Content-Type": "text/html",
    },
  });
}

/// Runs the HTTP server in the foreground.
///
/// Binds the requested hostname, not every interface: a server told to serve
/// localhost must not be reachable from the whole network (cli-daemon-spec §1).
export function serveHttp(host: string, port: number): void {
  boundHost = host;
  boundPort = port;

  // Startup lines are context — stderr, never stdout (§1).
  console.error(`${TOOL} serving on http://${host}:${port}/`);
  console.error(`  API: http://${host}:${port}/api/status`);

  Deno.serve({ hostname: host, port, onListen: () => {} }, handler);
}
